spring:
  application:
    name: productservice
  datasource: 
    driverClassName: com.mysql.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/productservice?autoreconnect=true"
    password: "root"
    username: "root"
    testOnBorrow: true
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1
    max-active: 15
    max-idle: 10
    max-wait: 8000

server:
  port: 8081